# Generated by Django 4.2.6 on 2023-11-01 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_desincorporacion'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Impresoras',
            new_name='Impresora',
        ),
    ]
