# Generated by Django 4.2.6 on 2023-11-01 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_desincorporacion_equipo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamento',
            name='nombre',
            field=models.CharField(default='No asignado', max_length=50),
        ),
    ]
