# Generated by Django 4.2.6 on 2023-11-01 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0006_alter_departamento_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='desincorporacion',
            name='usuario',
        ),
        migrations.AddField(
            model_name='desincorporacion',
            name='departamento',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='database.departamento'),
        ),
    ]
