# Generated by Django 4.2.6 on 2023-11-08 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0007_remove_desincorporacion_usuario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='desincorporacion',
            name='bien_nacional',
            field=models.CharField(default='000000', max_length=6),
        ),
        migrations.AddField(
            model_name='empleado',
            name='cedula',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='equipo',
            name='bien_nacional',
            field=models.CharField(default='000000', max_length=6),
        ),
        migrations.AddField(
            model_name='impresora',
            name='bien_nacional',
            field=models.CharField(default='000000', max_length=6),
        ),
        migrations.AddField(
            model_name='router',
            name='bien_nacional',
            field=models.CharField(default='000000', max_length=6),
        ),
        migrations.AddField(
            model_name='switch',
            name='bien_nacional',
            field=models.CharField(default='000000', max_length=6),
        ),
        migrations.AddField(
            model_name='telefono',
            name='bien_nacional',
            field=models.CharField(default='000000', max_length=6),
        ),
    ]
