# Generated by Django 4.2.6 on 2023-11-08 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0008_desincorporacion_bien_nacional_empleado_cedula_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='cargo',
            field=models.CharField(choices=[('Gerente', 'Gerente'), ('Jefe', 'Jefe'), ('Coordinador', 'Coordinador'), ('Especialista', 'Especialista'), ('Supervisor', 'Supervisor'), ('Diseñador', 'Diseñador'), ('Programador', 'Programador'), ('Soporte', 'Soporte'), ('Analista', 'Analista'), ('Sin cargo', 'Sin cargo')], default='Sin cargo', max_length=50),
        ),
    ]
