# Generated by Django 4.2.6 on 2023-11-08 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0009_alter_empleado_cargo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='desincorporacion',
            name='departamento',
        ),
        migrations.AlterField(
            model_name='desincorporacion',
            name='equipo',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='database.equipo'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='cargo',
            field=models.CharField(choices=[('Gerente', 'Gerente'), ('Jefe', 'Jefe'), ('Coordinador', 'Coordinador'), ('Especialista', 'Especialista'), ('Supervisor', 'Supervisor'), ('Diseñador', 'Diseñador'), ('Programador', 'Programador'), ('Soporte', 'Soporte'), ('Analista', 'Analista')], default='Sin cargo', max_length=50),
        ),
    ]
