# Generated by Django 4.2.6 on 2023-11-09 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0012_rename_equipo_desincorporacion_asignado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='desincorporacion',
            old_name='asignado',
            new_name='cedula_del_usuario_asociado',
        ),
    ]
