# Generated by Django 4.2.6 on 2023-11-09 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0013_rename_asignado_desincorporacion_cedula_del_usuario_asociado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='desincorporacion',
            old_name='cedula_del_usuario_asociado',
            new_name='cedula_del_usuario_asignado',
        ),
    ]
